disco-sheep:
    name: "Disco Sheep"
    enabled: true
    chance: 0.05
    material: 'WOOL'
    description:
        - 'Chance to spawn sheep that'
        - 'will randomly change color!'

exploding-redstone:
    name: "Exploding Redstone"
    enabled: true
    chance: 0.05
    material: 'REDSTONE'
    description:
        - 'Chance for redstone to'
        - 'explode when mined!'

chest-of-diamonds:
    name: "Chest O' Diamonds"
    enabled: true
    chance: 0.05
    material: 'DIAMOND'
    description:
        - 'Chance for a chest to spawn'
        - 'when mining diamonds!'

random-name:
    name: "Random Name"
    enabled: true
    chance: 0.05
    material: 'NAME_TAG'
    description:
        - 'Generate a random name when'
        - 'a mob spawns!'
