name: Ad237-t3
main: com.tenjava.entries.Ad237.t3.RandomEvents
version: '${project.version}'
author: Ad237
description: RandomEvents plugin for ten.java
commands:
   randomevents:
       description: RandomEvents command.
       aliases: [re]
